### ISSUE TITLE
 Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]       Unhandled exception in circuit

### ISSUE THREAD

**Issue by frankleib** [Inspirare-LLC/Radzen.Blazor.GridExportOptions#3]
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'IgvhxVy_X3LZ1FTBcYS4lYu0wOorcU6gc0xfUZm2wm8'.
      Microsoft.JSInterop.JSException: $ is not defined
ReferenceError: $ is not defined
    at Object.exportToExcel (https://localhost:5000/_content/radzen.blazor.gridexportoptions/radzen-grid-export-options.js:38:4)
    at https://localhost:5000/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at Tt.beginInvokeJSFromDotNet (https://localhost:5000/_framework/blazor.server.js:1:3475)
    at https://localhost:5000/_framework/blazor.server.js:1:71773
    at Array.forEach (<anonymous>)
    at Tt._invokeClientMethod (https://localhost:5000/_framework/blazor.server.js:1:71759)
    at Tt._processIncomingData (https://localhost:5000/_framework/blazor.server.js:1:69801)
    at bt.Tt.connection.onreceive (https://localhost:5000/_framework/blazor.server.js:1:64201)
    at WebSocket.o.onmessage (https://localhost:5000/_framework/blazor.server.js:1:48517)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Radzen.Blazor.GridExportOptions.RadzenGridExportOptions`1.ExportToExcel()
         at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item
)

**Comment by frankleib** [comment]
I added the project, I hope it help you to finde the problem, thanks :)

**Comment by mannylozada** [comment]
What was the resolution for this error? I'm having the same error
